name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test
      run: |
        python -m unittest discover -s tests

    - name: Build Docker image
      run: |
        docker build -t dpicatto/dani_app:latest .

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Verify Docker login
      run: |
        docker info
        cat ~/.docker/config.json

    - name: Push Docker image
      run: docker push dpicatto/dani_app:latest

    - name: Verify Docker login
      run: |
        docker info
        cat ~/.docker/config.json

    - name: Push Docker image
      run: |
        docker push dpicatto/dani_app:latest

    - name: Set up Terraform
      run: |
        cd terraform
        terraform init
        terraform import azurerm_resource_group.dani_app /subscriptions/${{ secrets.ARM_SUBSCRIPTION_ID }}/resourceGroups/dani_app_resources || true
        terraform apply -auto-approve
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
